### ISSUE TITLE
RubyDNS 2.0.0 available, can you please test.

### ISSUE THREAD

**Issue by ioquatix** [ShogunPanda/devdnsd#5]
We are preparing for 1.0.0 release of RubyDNS. Changes are mostly performance and bug fixing, tidy up code base.

https://github.com/ioquatix/rubydns/issues/28

If possible can you please test with latest 0.8.x and report back. We aim to do 1.0.0 release of RubyDNS by the end of this month. Thanks for your help!

**Comment by ioquatix** [comment]
RubyDNS 2.0.0-rc1 is now available and it's a big improvement, it would be great if you have time to check it out.

**Comment by ioquatix** [comment]
RubyDNS 2.0.0 has been released. Please consider updating and let me know any feedback. Thanks.

**Comment by ShogunPanda** [comment]
This is unmaintained. Closing issue for cleaning up.
